---
language: node_js

sandbox:
  vault:
    group: DMTRMONAKHOV_SANDBOX_GROUP

# test-string
env: SANDBOX_PRIVILEGED_CONTAINER=true AVOCADO_VERSION=64.0 REGISTRY=registry.yandex.net USER=dmtrmonakhov

before_script: sudo service docker start
script:
  # Build
  - docker build --network=host -t avocado-alpine:test -f Dockerfile.alpine .
  - docker tag avocado-alpine:test $REGISTRY/$USER/avocado-alpine:$AVOCADO_VERSION
  - docker tag avocado-alpine:test $REGISTRY/$USER/avocado-alpine:latest
  # Basic test
  - docker run --rm $REGISTRY/$USER/avocado-alpine:latest avocado run /bin/true /bin/uname
  # Push
  - docker login -u $USER -p $REGISTRY_OAUTH $REGISTRY
  - docker push $REGISTRY/$USER/avocado-alpine:$AVOCADO_VERSION
  - docker push $REGISTRY/$USER/avocado-alpine:latest
after_script: sudo service docker stop
